apps/beltExam/urls.py
from django.conf.urls import url
from . import views
app_name = 'beltExam'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^destination/(?P<id>\d+)$', views.destination, name='destination'),
    url(r'^addScreen$', views.addScreen, name='addScreen'),
    url(r'^addTrip$', views.addTrip, name='addTrip'),
    url(r'^join/(?P<id>\d+)$', views.join, name='join')
]

apps/login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^login$', views.login, name='login'),
    url('^register$', views.register, name='register'),
    url('^logout$', views.logout, name='logout'),
]

belt_exam/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^travels/', include('apps.beltExam.urls', namespace='travels')),
]

apps/beltExam/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
from ..login.models import User
# Create your models here.

class PlanManager(models.Manager):
    def myAdventures(self, userid):
        user = User.objects.get(id=userid)
        my_list = Plan.objects.filter(adventurers=user)
        return my_list
    def otherAdventures(self, userid):
        # fetch all plans for which the user is NOT an adventurer
        user = User.objects.get(id=userid)
        other_list = Plan.objects.exclude(adventurers=user)
        return other_list
    def otherAdventurers(self, planid):
        thisplan = Plan.objects.get(id=planid)
        thiscreator = thisplan.creator
        adventurers_list = (
            User.objects.filter(adventures=thisplan).exclude(id=thiscreator.id)
        )
        return adventurers_list
    def validAdventure(self, formdata):
        errors = []
        # no empty entries
        if len(formdata['destination']) < 1:
            errors.append('Please include a destination.')
        if len(formdata['description']) < 1:
            errors.append('Please include a description.')
        if len(formdata['startdate']) < 1:
            errors.append('Please include a travel start date.')
        if len(formdata['enddate']) < 1:
            errors.append('Please include a travel end date.')

        print formdata['startdate']
        print formdata['enddate']
        try:
            startdate = datetime.datetime.strptime(
                formdata['startdate'], '%Y-%m-%d'
            )
            enddate = datetime.datetime.strptime(
                formdata['enddate'], '%Y-%m-%d'
            )
            print enddate
            print startdate
            if startdate < datetime.datetime.today():
                errors.append('Travel start date must be in the future.')
            if enddate < startdate:
                errors.append('Travel end date cannot be before start date.')
        except ValueError:
            errors.append('Invalid Format')
        return errors
    def createAdventure(self, formdata, userid):
        new_adventure = Plan.objects.create(
            destination=formdata['destination'],
            description=formdata['description'],
            startdate=formdata['startdate'],
            enddate=formdata['enddate'],
            creator=User.objects.get(id=userid)
        )
        new_adventure.adventurers.add(new_adventure.creator)
        return new_adventure
    def joinAdventure(self, planid, userid):
        this_adventure = Plan.objects.get(id=planid)
        this_user = User.objects.get(id=userid)
        if this_user in this_adventure.adventurers.all():
            return this_adventure
        else:
            this_adventure.adventurers.add(this_user)
            return this_adventure

class Plan(models.Model):
    destination = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    startdate = models.DateTimeField()
    enddate = models.DateTimeField()
    creator = models.ForeignKey(User, related_name='created')
    adventurers = models.ManyToManyField(User, related_name='adventures')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = PlanManager()

apps/beltExam/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from ..login.models import User
from .models import Plan

# Create your views here.
def index(request):
    context = {
        'user': User.objects.filter(id=request.session['id']),
        'mytrips': Plan.objects.myAdventures(request.session['id']),
        'othertrips': Plan.objects.otherAdventures(request.session['id']),
    }
    return render(request, 'beltExam/index.html',context)

def destination(request, id):
    print User.objects.get(id=request.session['id']).adventures
    print User.objects.get(id=request.session['id']).created
    try:
        this_plan = Plan.objects.get(id=id)
        context = {
            'plan': this_plan,
            'others': Plan.objects.otherAdventurers(id)
        }
        return render(request, 'beltExam/destination.html', context)
    except ObjectDoesNotExist:
        return redirect(reverse('travels:index'))

def addScreen(request):
    return render(request, 'beltExam/add.html')

def join(request, id):
    Plan.objects.joinAdventure(id, request.session['id'])
    return redirect(reverse('travels:index'))

def addTrip(request):
    if request.method == 'POST':
        errors = Plan.objects.validAdventure(request.POST)
        if errors:
            for each in errors:
                messages.error(request, each)
            return redirect(reverse('travels:addScreen'))
        else:
            Plan.objects.createAdventure(request.POST, request.session['id'])
            return redirect(reverse('travels:index'))
    return redirect(reverse('travels:addScreen'))

apps/beltExam/templates/beltExam/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Add a Trip</title>
  {% load staticfiles %}
  <link href="{% static 'beltExam/trip-style.css' %}" rel="stylesheet">
</head>
<body>
  <a href="{% url 'travels:index' %}"><button type="button">Home</button></a>
  <a href="{% url 'login:logout' %}"><button type="button">Logout</button></a>
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
  <form action="{% url 'beltExam:addTrip' %}"method='POST'>
    {% csrf_token %}
    <h3>Add a Trip</h3>
    <label for="destination">Destination:</label>
    <input type="text" id="destination" name="destination"><br>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description"><br>
    <label for="startdate">Travel Date From:</label>
    <input type="date" id="startdate" name="startdate" placeholder="YYYY-MM-DD"><br>
    <label for="enddate">Travel Date To:</label>
    <input type="date" id="enddate" name="enddate" placeholder="YYYY-MM-DD"><br>
    <input type="submit" name="submit" value="Submit">
  </form>
</body>
</html>

apps/beltExam/templates/beltExam/destination.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Destination</title>
  {% load staticfiles %}
  <link href="{% static 'beltExam/trip-style.css' %}" rel="stylesheet">
</head>
<body>
<header>
  <h1>GTP for {{ plan.destination }}</h1>
  <a href="{% url 'travels:index' %}">Home</a>
  <a href="{% url 'login:logout' %}">Logout</a>
</header>

<p>Planned By: {{ plan.creator.first_name }}</p>
<p>Description: {{ plan.description }}</p>
<p>Travel Date From: {{ plan.startdate|date:'M d Y' }}</p>
<p>Travel Date To: {{ plan.enddate|date:'M d Y' }}</p>
<h2>Other users joining the trip:</h2>


<ul>
  {% for joiner in others %}
    <li>{{ joiner.first_name }}</li>
  {% endfor %}
</ul>
</body>
</html>

apps/beltExam/templates/beltExam/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Trip Home</title>
  {% load staticfiles %}
  <link href="{% static 'beltExam/style.css' %}" rel="stylesheet">
</head>
<body>
  <header>
     <h1>Hello {{ user.0.first_name }}. Welcome to your GTP!</h1>
     <a href="{% url 'login:logout' %}">Logout</a>
  </header>
   {% for message in messages %}
     <p>{{ message }}</p>
   {% endfor %}

   <div class="plans">

    <h3>Your Scheduled Trips:</h3>
    {%if mytrips%}
    <table>
      <thead>
        <tr>
          <td>Destination</td>
          <td>Travel Start Date</td>
          <td>Travel End Date</td>
          <td>Plan</td>
        </tr>
      </thead>
        {% for trip in mytrips %}
      <tbody>
          <tr>
            <td><a href="{% url 'travels:destination' id=trip.id %}">{{ trip.destination }}</a></td>
            <td>{{ trip.startdate|date:'M d Y' }}</td>
            <td>{{ trip.enddate|date:'M d Y' }}</td>
            <td>{{ trip.description }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {%else%}
      <p>Get going! Schedule a trip</p>
    {%endif%}
    <a href="{% url 'travels:addScreen' %}"><button type="button">Add Plans</button></a>
  </div>


<div class="plans">
  <h3>Others' Travel Plans: </h3>
  {%if othertrips%}
  <table>
    <thead>
      <tr>
        <td>Name</td>
        <td>Destination</td>
        <td>Travel Start Date</td>
        <td>Travel End Date</td>
        <td>Do You Want to Join?</td>
      </tr>
    </thead>
    <tbody>
        {% for trip in othertrips %}
          <tr>
            <td>{{ trip.creator.first_name }}</td>
            <td><a href="{% url 'travels:destination' id=trip.id %}">{{ trip.destination }}</a></td>
            <td>{{ trip.startdate|date:'M d Y' }}</td>
            <td>{{ trip.enddate|date:'M d Y' }}</td>
            <td><a href="{% url 'travels:join' id=trip.id %}">Join</a></td>
          </tr>
        {% endfor %}
      {%else%}
        <p>There are no trips left to join!</p>
      {%endif%}
     </tbody>
   </table>
</div>

</body>
</html>